set(CURL_DIR ${3RDPARTY_DIR}/curl)

set(CURL_USE_LIBPSL OFF)
set(ENABLE_UNICODE ON)
set(HTTP_ONLY ON)
set(CURL_DISABLE_KERBEROS_AUTH ON)
set(CURL_DISABLE_AWS ON)
set(CURL_DISABLE_WEBSOCKETS ON)
set(USE_NGHTTP2 OFF)
set(USE_NGTCP2 OFF)

set(ENABLE_CURL_MANUAL OFF)
set(CURL_DISABLE_INSTALL ON)
set(CURL_ENABLE_EXPORT_TARGET OFF)

set(BUILD_STATIC_CURL ON)
set(BUILD_CURL_EXE OFF)
set(BUILD_LIBCURL_DOCS OFF)
set(BUILD_MISC_DOCS OFF)
set(BUILD_EXAMPLES OFF)
set(BUILD_TESTING OFF)

if (MSVC)
    set(HAVE_SIZEOF_SSIZE_T FALSE)
endif()

add_subdirectory(${CURL_DIR})

# add zlib
target_compile_definitions(libcurl_object PRIVATE HAVE_LIBZ=1)
target_include_directories(libcurl_object PRIVATE ${zlib_BINARY_DIR})
