set(JSONC_DIR ${3RDPARTY_DIR}/json-c)

set(BUILD_APPS OFF)
add_subdirectory(${JSONC_DIR})

list(APPEND CLAMWIN_INCLUDES ${JSONC_DIR} ${json-c_BINARY_DIR})
list(APPEND CLAMWIN_LIBRARIES json-c)

install(FILES ${JSONC_DIR}/COPYING DESTINATION ${CMAKE_INSTALL_PREFIX}/copyright RENAME COPYING.json-c)
