set(LIBXML2_DIR ${3RDPARTY_DIR}/libxml2)

set(LIBXML2_WITH_ICONV OFF)
set(LIBXML2_WITH_PYTHON OFF)
set(LIBXML2_WITH_MODULES OFF)
set(LIBXML2_WITH_PROGRAMS OFF)
set(LIBXML2_WITH_TESTS OFF)
set(LIBXML2_WITH_DEBUG OFF)

add_subdirectory(${LIBXML2_DIR} EXCLUDE_FROM_ALL)
target_compile_options(LibXml2 PRIVATE $<$<C_COMPILER_ID:MSVC>:/wd4244 /wd4267>)

list(APPEND CLAMWIN_INCLUDES ${LIBXML2_DIR}/include)
list(APPEND CLAMWIN_LIBRARIES LibXml2)

install(FILES ${LIBXML2_DIR}/Copyright DESTINATION ${CMAKE_INSTALL_PREFIX}/copyright RENAME COPYING.libxml2)
