set(OPENSSL_ROOT_DIR ${3RDPARTY_DIR}/openssl/lib/mingw/legacy)

find_library(OPENSSL_SSL_LIBRARY
    NAMES ssl libssl
    HINTS ${OPENSSL_ROOT_DIR}
    REQUIRED
)

find_library(OPENSSL_CRYPTO_LIBRARY
    NAMES crypto libcrypto
    HINTS ${OPENSSL_ROOT_DIR}
    REQUIRED
)

message(STATUS "OpenSSL libraries: ${OPENSSL_SSL_LIBRARY} ${OPENSSL_CRYPTO_LIBRARY}")

set(OPENSSL_INCLUDE_DIR ${3RDPARTY_DIR}/openssl/include)
list(APPEND CLAMWIN_INCLUDES ${OPENSSL_INCLUDE_DIR})

install(FILES ${3RDPARTY_DIR}/openssl/LICENSE.txt DESTINATION ${CMAKE_INSTALL_PREFIX}/copyright RENAME openssl.txt)
