set(PCRE2_DIR ${3RDPARTY_DIR}/pcre2)

set(PCRE2_BUILD_PCRE2GREP OFF)
set(PCRE2_BUILD_TESTS OFF)

set(PCRE2_SUPPORT_LIBBZ2 OFF)
set(PCRE2_SUPPORT_LIBZ OFF)
set(PCRE2_SUPPORT_LIBEDIT OFF)
set(PCRE2_SUPPORT_LIBREADLINE OFF)

add_subdirectory(${PCRE2_DIR} EXCLUDE_FROM_ALL)

list(APPEND CLAMWIN_INCLUDES "${PCRE2_BINARY_DIR}/interface")
list(APPEND CLAMWIN_LIBRARIES pcre2-8-static)

install(FILES ${PCRE2_DIR}/LICENCE.md DESTINATION ${CMAKE_INSTALL_PREFIX}/copyright RENAME pcre2.md)
