set(PCRE2_DIR ${3RDPARTY_DIR}/pcre2)

set(PCRE2_BUILD_PCRE2GREP OFF)
set(PCRE2_BUILD_TESTS OFF)

add_subdirectory(${PCRE2_DIR})

list(APPEND CLAMWIN_INCLUDES ${PCRE2_BINARY_DIR})
list(APPEND CLAMWIN_LIBRARIES pcre2-8-static)

install(FILES ${PCRE2_DIR}/LICENCE.md DESTINATION ${CMAKE_INSTALL_PREFIX}/copyright RENAME COPYING.pcre2.md)
