set(ZLIB_DIR ${3RDPARTY_DIR}/zlib-ng)

set(ZLIB_COMPAT ON)
set(ZLIB_ENABLE_TESTS OFF)
set(ZLIBNG_ENABLE_TESTS OFF)
set(WITH_GTEST OFF)

add_subdirectory(${ZLIB_DIR})

list(APPEND CLAMWIN_INCLUDES ${zlib_BINARY_DIR})
list(APPEND CLAMWIN_LIBRARIES zlib)

install(FILES ${ZLIB_DIR}/LICENSE.md DESTINATION ${CMAKE_INSTALL_PREFIX}/copyright RENAME LICENSE.zlib-ng.md)
